### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by srollins01**
Added link to API docs.

### CODE REVIEW

**Review by ayau8 — COMMENTED** [review]
Thanks Sarah. No issue with the update for README but I notice that when I try to scroll all the way down on bump.sh, it seems that "Deletes a user" on the side bar doesn't appear as green accordingly and is pointing towards the previous endpoint. We may want to revise it before seeking further approval. Thanks again!

**Comment by srollins01** [comment]
Hi @ayau8, it seems to be displaying okay on my side. 
deletes a user
Could you double-check the url? For delete it should automatically change to: https://bump.sh/menternshift/doc/menternshift/operation/operation-delete-api-v1-users-parameter

**Comment by ayau8** [comment]
Hey @srollins01, it should be due to the % of zoom in & out. It appears okay if I zoom out so I guess that shouldn't be an issue then

Screenshot 2024-04-02 at 6 38 47 PM

**Review by ayau8 — APPROVED** [review]

**Review by achpsident — APPROVED** [review]
LGTM, my only suggestion is to use a more descriptive branch name next time.

**Pull request merged**
