### PR TITLE
add factory_bot_rails & faker

### PR DESCRIPTION
**Pull request by ayau8**
Adding factory_bot_rails GEM which lets us generate object instances with default values easily with rails-specific features and integrations, and eliminates lots of boilerplate.

### CODE REVIEW

**Review by achpsident — COMMENTED** [review]
Looks good, but can we try creating a User factory to see if any additional configuration is needed?

**Comment by ayau8** [comment]
A user factory is created where no additional configuration is needed to pass the spec testing

However, we may consider further improving the user factory with the following:
1) Install faker GEM to generate fake data, for example, first_name / username, etc.
2) Use sequences and faker to generate unique and realistic email address (even though we haven't had the validation parts set up, it usually requires uniqueness)

**Comment by achpsident** [comment]
> A user factory is created where no additional configuration is needed to pass the spec testing
> 
> However, we may consider further improving the user factory with the following:
> 
> 1. Install faker GEM to generate fake data, for example, first_name / username, etc.
> 2. Use sequences and faker to generate unique and realistic email address (even though we haven't had the validation parts set up, it usually requires uniqueness)

Nicely done with the initial setup, let's handle those further improvements now while they're fresh in our minds. Add faker if you think it'll be helpful, we can already use sequences at the moment to do stuff like `sequence(:email) { |n| "username#{n}@example.com" }`, so let's do so.

**Review by achpsident — COMMENTED** [review]
Looks good, but as you said, let's add the sequencing to the User factory so as to be able to create multiple users easily.

**Comment by ayau8** [comment]
The User factory is updated with 1) the installation of faker GEM and the inclusion of relevant faker (i.e. name) and 2) email sequencing, both of which further improve and facilitate the creation of multiple users down the road

The title of this PR has been updated from "add factory_bot_rails" to "add factory_bot_rails & faker" to reflect the latest update of GEM package

**Review by achpsident — APPROVED** [review]
LGTM

**Pull request merged**
